name: LSIF
on:
  - push
jobs:
  build:
    name: Build and push LSIF data
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: OCaml setup
          uses: avsm/setup-ocaml@master
            with:
              ocaml-version: '4.08.1'
        - run: opam pin add comby.dev -n .
        - run: opam depext -yt comby
        - run: opam install -t . --deps-only
        - run: opam exec -- dune build
#       - name: Generate LSIF data
#         uses: rvantonder/lsif-ocaml-action@master # TODO
#         with:
#             verbose: 'true'
#       - name: Upload LSIF data
#         uses: sourcegraph/lsif-upload-action@master
#         continue-on-error: true
#         with:
#           endpoint: https://sourcegraph.com
#           github_token: ${{ secrets.GITHUB_TOKEN }}
